bg_items:
  - area:
      - 143
      - 256
      - 340
      - 313
    contents: 权利人
    fold: false
    mode: h_merge
    ed_thresh: 0
  - area:
      - 266
      - 1380
      - 448
      - 1455
    contents: 使用期限
    fold: true
    mode: common
    ed_thresh: 0
  - area:
      - 1398
      - 211
      - 1576
      - 275
    contents: 幢号
    fold: false
    mode: h_merge
    ed_thresh: 0
  - area:
      - 1315
      - 1264
      - 1477
      - 1333
    contents: 填证单位：
    fold: false
    mode: common
    ed_thresh: 1
  - area:
      - 1395
      - 353
      - 1584
      - 408
    contents: 室号或部位
    fold: true
    mode: common
    ed_thresh: 0
  - area:
      - 144
      - 420
      - 340
      - 475
    contents: 房地坐落
    fold: true
    mode: common
    ed_thresh: 0
  - area:
      - 247
      - 528
      - 451
      - 599
    contents: 权属性质
    fold: true
    mode: common
    ed_thresh: 0
  - area:
      - 223
      - 627
      - 479
      - 697
    contents: 使用权取得方式
    fold: true
    mode: common
    ed_thresh: 0
  - area:
      - 245
      - 845
      - 448
      - 908
    contents: 宗地号
    fold: false
    mode: h_merge
    ed_thresh: 0
  - area:
      - 238
      - 938
      - 464
      - 1017
    contents: 宗地（丘）面积
    fold: false
    mode: common
    ed_thresh: 2
  - area:
      - 249
      - 1043
      - 455
      - 1116
    contents: 使用权面积
    fold: true
    mode: common
    ed_thresh: 0
  - area:
      - 339
      - 1146
      - 470
      - 1199
    contents: 独用
    fold: false
    mode: common
    ed_thresh: 0
  - area:
      - 341
      - 1257
      - 471
      - 1317
    contents: 分摊
    fold: true
    mode: common
    ed_thresh: 0
  - area:
      - 1393
      - 485
      - 1580
      - 546
    contents: 建筑面积
    fold: true
    mode: common
    ed_thresh: 0
  - area:
      - 1397
      - 621
      - 1579
      - 678
    contents: 建筑类型
    fold: true
    mode: common
    ed_thresh: 0
  - area:
      - 1397
      - 892
      - 1588
      - 948
    contents: 总层数
    fold: false
    mode: h_merge
    ed_thresh: 0
  - area:
      - 1394
      - 1022
      - 1587
      - 1084
    contents: 竣工日期
    fold: true
    mode: common
    ed_thresh: 0
  - area:
      - 147
      - 713
      - 208
      - 774
    contents: 土
    fold: true
    mode: common
    ed_thresh: 0
  - area:
      - 147
      - 885
      - 206
      - 942
    contents: 地
    fold: true
    mode: common
    ed_thresh: 0
  - area:
      - 1312
      - 350
      - 1364
      - 414
    contents: 房
    fold: true
    mode: common
    ed_thresh: 0
  - area:
      - 1309
      - 523
      - 1363
      - 586
    contents: 屋
    fold: true
    mode: common
    ed_thresh: 0
  - area:
      - 1846
      - 1272
      - 2057
      - 1323
    contents: 房地产登记处
    fold: true
    mode: common
    ed_thresh: 0
  - area:
      - 1854
      - 1492
      - 2022
      - 1544
    contents: 面积单位：
    fold: true
    mode: common
    ed_thresh: 0
  - area:
      - 2022
      - 1491
      - 2141
      - 1544
    contents: 平方米
    fold: true
    mode: common
    ed_thresh: 0
  - area:
      - 247
      - 1176
      - 299
      - 1232
    contents: 其
    fold: true
    mode: common
    ed_thresh: 0
  - area:
      - 245
      - 1285
      - 295
      - 1334
    contents: 中
    fold: true
    mode: common
    ed_thresh: 0
fg_items:
  - area:
      - 373
      - 223
      - 938
      - 348
    item_name: name
    item_type: ''
    fold: false
    filter_regexs: []
    ioo_thresh: 0
    item_pre_func: _pre_func_name
    item_post_func: _post_func_name
  - area:
      - 373
      - 404
      - 962
      - 484
    item_name: address
    item_type: ''
    fold: false
    filter_regexs: []
    ioo_thresh: 0
    item_pre_func: _pre_func_address
    item_post_func: _post_func_address
  - area:
      - 497
      - 532
      - 978
      - 600
    item_name: prevelige
    item_type: ''
    fold: true
    filter_regexs: []
    ioo_thresh: 0
    item_pre_func: _pre_func_prevelige
    item_post_func: _post_func_prevelige
  - area:
      - 505
      - 624
      - 981
      - 694
    item_name: get_way
    item_type: ''
    fold: true
    filter_regexs: []
    ioo_thresh: 0
    item_pre_func: _pre_func_get_way
    item_post_func: _post_func_get_way
  - area:
      - 508
      - 842
      - 997
      - 905
    item_name: land_no
    item_type: ''
    fold: true
    filter_regexs: []
    ioo_thresh: 0
    item_pre_func: _pre_func_land_no
    item_post_func: _post_func_land_no
  - area:
      - 508
      - 943
      - 950
      - 1006
    item_name: land_area
    item_type: ''
    fold: true
    filter_regexs: []
    ioo_thresh: 0
    item_pre_func: _pre_func_land_area
    item_post_func: _post_func_land_area
  - area:
      - 503
      - 1051
      - 945
      - 1111
    item_name: use_area
    item_type: ''
    fold: true
    filter_regexs: []
    ioo_thresh: 0
    item_pre_func: _pre_func_use_area
    item_post_func: _post_func_use_area
  - area:
      - 502
      - 1157
      - 919
      - 1221
    item_name: private_erea
    item_type: ''
    fold: true
    filter_regexs: []
    ioo_thresh: 0
    item_pre_func: _pre_func_private_erea
    item_post_func: _post_func_private_erea
  - area:
      - 512
      - 1277
      - 914
      - 1343
    item_name: com_area
    item_type: ''
    fold: true
    filter_regexs: []
    ioo_thresh: 0
    item_pre_func: _pre_func_com_area
    item_post_func: _post_func_com_area
  - area:
      - 508
      - 1404
      - 922
      - 1526
    item_name: use_time
    item_type: ''
    fold: true
    filter_regexs: []
    ioo_thresh: 0
    item_pre_func: _pre_func_use_time
    item_post_func: _post_func_use_time
  - area:
      - 1629
      - 206
      - 1929
      - 286
    item_name: floor_no
    item_type: ''
    fold: true
    filter_regexs: []
    ioo_thresh: 0
    item_pre_func: _pre_func_floor_no
    item_post_func: _post_func_floor_no
  - area:
      - 1633
      - 346
      - 1924
      - 418
    item_name: room_no
    item_type: ''
    fold: true
    filter_regexs: []
    ioo_thresh: 0
    item_pre_func: _pre_func_room_no
    item_post_func: _post_func_room_no
  - area:
      - 1635
      - 475
      - 1921
      - 554
    item_name: build_area
    item_type: ''
    fold: true
    filter_regexs: []
    ioo_thresh: 0
    item_pre_func: _pre_func_build_area
    item_post_func: _post_func_build_area
  - area:
      - 1631
      - 607
      - 1975
      - 687
    item_name: build_type
    item_type: ''
    fold: true
    filter_regexs: []
    ioo_thresh: 0
    item_pre_func: _pre_func_build_type
    item_post_func: _post_func_build_type
  - area:
      - 1646
      - 881
      - 2107
      - 952
    item_name: all_layer
    item_type: ''
    fold: true
    filter_regexs: []
    ioo_thresh: 0
    item_pre_func: _pre_func_all_layer
    item_post_func: _post_func_all_layer
  - area:
      - 1659
      - 1011
      - 2146
      - 1090
    item_name: done_time
    item_type: ''
    fold: true
    filter_regexs: []
    ioo_thresh: 0
    item_pre_func: _pre_func_done_time
    item_post_func: _post_func_done_time
  - area:
      - 1512
      - 1235
      - 1819
      - 1369
    item_name: company
    item_type: ''
    fold: true
    filter_regexs: []
    ioo_thresh: 0
    item_pre_func: _pre_func_company
    item_post_func: _post_func_company
above_items: []
region_items: []
version: 2
above_offset_method: ''
