# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

from ocr_structuring.protos import structuring_pb2 as ocr__structuring_dot_protos_dot_structuring__pb2


class StructuringStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.Process = channel.unary_unary(
        '/ocr_structuring.Structuring/Process',
        request_serializer=ocr__structuring_dot_protos_dot_structuring__pb2.StructuringRequest.SerializeToString,
        response_deserializer=ocr__structuring_dot_protos_dot_structuring__pb2.StructuringResponse.FromString,
        )
    self.ProcessRotated = channel.unary_unary(
        '/ocr_structuring.Structuring/ProcessRotated',
        request_serializer=ocr__structuring_dot_protos_dot_structuring__pb2.StructuringRequestRotated.SerializeToString,
        response_deserializer=ocr__structuring_dot_protos_dot_structuring__pb2.StructuringResponse.FromString,
        )
    self.ProcessMultiImage = channel.unary_unary(
        '/ocr_structuring.Structuring/ProcessMultiImage',
        request_serializer=ocr__structuring_dot_protos_dot_structuring__pb2.MultiImageStructuringRequest.SerializeToString,
        response_deserializer=ocr__structuring_dot_protos_dot_structuring__pb2.StructuringResponse.FromString,
        )


class StructuringServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def Process(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def ProcessRotated(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def ProcessMultiImage(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_StructuringServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'Process': grpc.unary_unary_rpc_method_handler(
          servicer.Process,
          request_deserializer=ocr__structuring_dot_protos_dot_structuring__pb2.StructuringRequest.FromString,
          response_serializer=ocr__structuring_dot_protos_dot_structuring__pb2.StructuringResponse.SerializeToString,
      ),
      'ProcessRotated': grpc.unary_unary_rpc_method_handler(
          servicer.ProcessRotated,
          request_deserializer=ocr__structuring_dot_protos_dot_structuring__pb2.StructuringRequestRotated.FromString,
          response_serializer=ocr__structuring_dot_protos_dot_structuring__pb2.StructuringResponse.SerializeToString,
      ),
      'ProcessMultiImage': grpc.unary_unary_rpc_method_handler(
          servicer.ProcessMultiImage,
          request_deserializer=ocr__structuring_dot_protos_dot_structuring__pb2.MultiImageStructuringRequest.FromString,
          response_serializer=ocr__structuring_dot_protos_dot_structuring__pb2.StructuringResponse.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'ocr_structuring.Structuring', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
